SELECT
    c.[CLIENTID]
    ,c.[CLIENTNAME]
    ,pt.[PORTID]
    ,pt.[DESCRPN] as [PORTNAME]
    ,pt.[ACCTMNGR]
    ,pj.[PROJID]
    ,pj.[PROJNAME]
    ,pj.[ASSETMGR]
    ,pj.[INACTIVE] as [PROJ_INACTIVE]
    ,e.[ENTITYID]
    ,e.[ENTTYPE]
    ,e.[COUNTRY] as [ENTITY_COUNTRY]
    ,e.[STATE] as [ENTITY_STATE]
    ,e.[CITY] as [ENTITY_CITY]
    ,b.[BLDGID]
    ,b.[BLDGNAME]
    ,b.[CITY] as [BLDG_CITY]
    ,b.[STATE] as [BLDG_STATE]
    ,b.[PROPTYPE]
    ,b.[INACTIVE] as [BLDG_INACTIVE]
FROM [MRI_AUNZ].[dbo].[BLDG] b WITH (nolock)
    LEFT JOIN [MRI_AUNZ].[dbo].[ENTITY] e WITH (nolock) ON e.[ENTITYID] = b.[ENTITYID]
    LEFT JOIN [MRI_AUNZ].[dbo].[PROJ] pj WITH (nolock) ON pj.[PROJID] = e.[PROJID]
    LEFT JOIN [MRI_AUNZ].[dbo].[PORT] pt WITH (nolock) ON pt.[PORTID] = pj.[PORTID]
    LEFT JOIN [MRI_AUNZ].[dbo].[CLIENT] c WITH (nolock) ON c.[CLIENTID] = pt.[CLIENTID] 

