SELECT
    c.[CLIENTID]
    ,c.[CLIENTNAME]
    ,pt.[PORTID]
    ,pt.[DESCRPN] as [PORTNAME]
    ,pt.[ACCTMNGR]
    ,pj.[PROJID]
    ,pj.[PROJNAME]
    ,pj.[ASSETMGR]
    ,pj.[INACTIVE] as [PROJ_INACTIVE]
    ,e.[ENTITYID]
    ,e.[ENTTYPE]
    ,e.[COUNTRY]
    ,e.[STATE]
    ,e.[CITY]
    ,g.[OWNERID]
    ,g.[PERCENT]
    ,gn.[NAME] as [OWNER_NAME]
    ,b.[LEGALNAME]
    ,b.[BLDGID]
    ,b.[BLDGNAME]
    ,b.[CITY]
    ,b.[STATE]
    ,b.[INACTIVE]
FROM [MRI_AUNZ].[dbo].[CLIENT] c
    LEFT JOIN [MRI_AUNZ].[dbo].[PORT] pt ON c.[CLIENTID] = pt.[CLIENTID]
    LEFT JOIN [MRI_AUNZ].[dbo].[PROJ] pj ON pt.[PORTID] = pj.[PORTID]
    LEFT JOIN [MRI_AUNZ].[dbo].[ENTITY] e ON pj.[PROJID] = e.[PROJID]
    LEFT JOIN [MRI_AUNZ].[dbo].[GOWN] g ON e.[ENTITYID] = g.[ENTITYID]
    LEFT JOIN [MRI_AUNZ].[dbo].[GNAM] gn ON g.[OWNERID] = gn.[OWNERID]
    LEFT JOIN [MRI_AUNZ].[dbo].[BLDG] b ON e.[ENTITYID] = b.[ENTITYID]

WHERE c.[CLIENTID] = 'SCA'

