-- non MRI tables
SELECT [TABLENAME],[DESCRPN],[CREATEDT],[OWNER],[APPLNID],[VALIDATION]
	,[LASTUPDT],[LASTUSER],[MRITABLE],[SYSTABLE]
  FROM [MRI_AUNZ].[dbo].[MRITable]
  WHERE [MRITABLE] = 'N'
  ORDER BY [CREATEDT];

SELECT *
FROM [MRI_AUNZ].[dbo].[MRIField]
WHERE [TABLENAME] = 'BLDG'
ORDER BY [FIELDNAME]

-- non MRI Fields in MRI tables
SELECT 
  [TABLENAME],[FIELDNAME],[DESCRPN],[FLDTYPE],[FLDLENGTH]
	,[FLDNDECS],[DBCOLUMN],[SYSFIELD],[LOOKUP],[VALIDATION]
	,[FLDDEFAULT],[REQUIRED],[MRIFIELD]
FROM [MRI_AUNZ].[dbo].[MRIField]
WHERE [MRIFIELD] = 'N'
  AND [TABLENAME] IN (
    SELECT mt.[TABLENAME]
    FROM [MRI_AUNZ].[dbo].[MRITable] as mt
      INNER JOIN [MRI_AUNZ].[INFORMATION_SCHEMA].[TABLES] as t ON mt.[TABLENAME] = t.[TABLE_NAME]
    WHERE t.[TABLE_TYPE] = 'BASE TABLE'
      AND mt.[MRITABLE] = 'Y'
  )
ORDER BY [TABLENAME],[DBCOLUMN]


SELECT c.[TABLE_CATALOG],c.[TABLE_SCHEMA],c.[TABLE_NAME], COUNT(c.[COLUMN_NAME]) as [COLUMN_COUNT]
FROM [MRI_AUNZ].[INFORMATION_SCHEMA].[COLUMNS] as C
  INNER JOIN [MRI_AUNZ].[INFORMATION_SCHEMA].[TABLES] as t ON c.[TABLE_CATALOG] = t.[TABLE_CATALOG] AND c.[TABLE_SCHEMA] = t.[TABLE_SCHEMA] AND c.[TABLE_NAME] = t.[TABLE_NAME]
WHERE t.[TABLE_TYPE] = 'BASE TABLE'
GROUP BY c.[TABLE_CATALOG],c.[TABLE_SCHEMA],c.[TABLE_NAME]
ORDER BY [COLUMN_COUNT] DESC


 SELECT * FROM [MRI_AUNZ].[dbo].[MRIVPRI]
 SELECT * FROM [MRI_AUNZ].[dbo].[MRIVSUB]

 SELECT * FROM [MRI_AUNZ].[dbo].[MRIRPTS] WHERE [RPTNAME] LIKE '%CUS%'
 SELECT TOP 100 * FROM [MRI_AUNZ].[dbo].[MRIREPORTLIST] WITH (nolock) ORDER BY [RUNDATE] DESC

 SELECT TOP 100 * FROM [MRI_AUNZ].[dbo].[RPT_ReportUsage] WITH (nolock) ORDER BY [RequestStartTime] DESC

SELECT TOP 100 * FROM [MRI_AUNZ].[dbo].[RPT_ReportUsageParameter] WITH (nolock) ORDER BY [CreatedBy] DESC
 
SELECT TOP 100 * FROM [MRI_AUNZ].[dbo].[RPT_ReportUsage] WITH (nolock) WHERE [ReportUsageID] = 577	


  SELECT [RPTNAME],[DESCRPTN],[APPLID],[GROUPDESC],[LASTDATE],[USERID],[MRIREPORT]
	,[HIDE],[REPORTTYPE],[WEB],[SITEID],[COMMENTS],[UPDATELOG],[RevisionNumber]
	,[USECTDATE],[USECOUNT],[LASTRUN],[RUNBY],[HGROUPID],[LASTUSER]
  FROM [MRI_AUNZ].[dbo].[MRIRPTS]
  WHERE [RPTNAME] LIKE '%CUST%'

  SELECT [VIEWNAME],[TABLEID],[FORMNO],[CNTRLNAME],[CNTRLNMBR]
	,[TABINDEX],[PROPERTIES],[MISC],[FORMID]
  FROM [MRI_AUNZ].[dbo].[MRIVOBJ] WITH (nolock)
  WHERE [MISC] LIKE '%.PORTID%'
  AND [TABLEID] <> 'WEB'


SELECT *
  FROM [MRI_AUNZ].[dbo].[MRIVOBJ] WITH (nolock)
  WHERE [VIEWNAME] = 'CBRE'
	AND [TABLEID] = 'BLDG'
	AND [MISC] LIKE '%CLNT%'
ORDER BY [FORMNO],[CNTRLNMBR],[TABINDEX]

