SELECT [TABLENAME],[DESCRPN],[CREATEDT],[OWNER],[APPLNID],[VALIDATION]
	,[LASTUPDT],[LASTUSER],[MRITABLE],[SYSTABLE]
  FROM [MRI_AUNZ].[dbo].[MRITable]
  WHERE [MRITABLE] = 'N'
  ORDER BY [CREATEDT];

SELECT [TABLENAME],[FIELDNAME],[DESCRPN],[FLDTYPE],[FLDLENGTH]
	,[FLDNDECS],[DBCOLUMN],[SYSFIELD],[LOOKUP],[VALIDATION]
	,[FLDDEFAULT],[REQUIRED],[MRIFIELD]
  FROM [MRI_AUNZ].[dbo].[MRIField]
  WHERE [MRIFIELD] = 'N'
  ORDER BY [TABLENAME],[DBCOLUMN]

  SELECT [RPTNAME],[DESCRPTN],[APPLID],[GROUPDESC],[LASTDATE],[USERID],[MRIREPORT]
	,[HIDE],[REPORTTYPE],[WEB],[SITEID],[COMMENTS],[UPDATELOG],[RevisionNumber]
	,[USECTDATE],[USECOUNT],[LASTRUN],[RUNBY],[HGROUPID],[LASTUSER]
  FROM [MRI_AUNZ].[dbo].[MRIRPTS]
  WHERE [RPTNAME] LIKE '%CUST%'

  SELECT [VIEWNAME],[TABLEID],[FORMNO],[CNTRLNAME],[CNTRLNMBR]
	,[TABINDEX],[PROPERTIES],[MISC],[FORMID]
  FROM [MRI_AUNZ].[dbo].[MRIVOBJ] WITH (nolock)
  WHERE [MISC] LIKE '%.PORTID%'
  AND [TABLEID] <> 'WEB'


SELECT *
  FROM [MRI_AUNZ].[dbo].[MRIVOBJ] WITH (nolock)
  WHERE [VIEWNAME] = 'CBRE'
	AND [TABLEID] = 'BLDG'
	AND [MISC] LIKE '%CLNT%'
ORDER BY [FORMNO],[CNTRLNMBR],[TABINDEX]

