--
-- Logins for Windows accounts
--
-- Login: APACKF\PAS Development
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\PAS Development')
BEGIN
	CREATE LOGIN [APACKF\PAS Development] FROM WINDOWS 
	WITH DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British];
	RAISERROR('INFO: Login [APACKF\PAS Development] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [APACKF\PAS Development] already exists.',10,1) WITH NOWAIT;
END 

-- Login: APACKF\PAS Development Administrator Group
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\PAS Development Administrator Group')
BEGIN
	CREATE LOGIN [APACKF\PAS Development Administrator Group] FROM WINDOWS 
	WITH DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British];
	RAISERROR('INFO: Login [APACKF\PAS Development Administrator Group] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [APACKF\PAS Development Administrator Group] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: APACKF\Information Technology - PAST
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\Information Technology - PAST')
BEGIN
	CREATE LOGIN [APACKF\Information Technology - PAST] FROM WINDOWS 
	WITH DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British];
	RAISERROR('INFO: Login [APACKF\Information Technology - PAST] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [APACKF\Information Technology - PAST] already exists.',10,1) WITH NOWAIT;
END 

-- Login: APACKF\wi2deploy
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\wi2deploy')
BEGIN
	CREATE LOGIN [APACKF\wi2deploy] FROM WINDOWS 
	WITH DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British];
	RAISERROR('INFO: Login [APACKF\wi2deploy] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [APACKF\wi2deploy] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: APACKF\vreports
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\vreports')
BEGIN
	CREATE LOGIN [APACKF\vreports] FROM WINDOWS 
	WITH DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British];
	RAISERROR('INFO: Login [APACKF\vreports] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [APACKF\vreports] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: APACKF\visionimageup
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\visionimageup')
BEGIN
	CREATE LOGIN [APACKF\visionimageup] FROM WINDOWS 
	WITH DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British];
	RAISERROR('INFO: Login [APACKF\visionimageup] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [APACKF\visionimageup] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: APACKF\strestricted
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\strestricted')
BEGIN
	CREATE LOGIN [APACKF\strestricted] FROM WINDOWS 
	WITH DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British];
	RAISERROR('INFO: Login [APACKF\strestricted] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [APACKF\strestricted] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: APACKF\SQLService
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\SQLService')
BEGIN
	CREATE LOGIN [APACKF\SQLService] FROM WINDOWS 
	WITH DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British];
	RAISERROR('INFO: Login [APACKF\SQLService] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [APACKF\SQLService] already exists.',10,1) WITH NOWAIT;
END 

--
-- Logins for SQL Server accounts
--
-- Login: wi2_user
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'wi2_user')
BEGIN
	CREATE LOGIN [wi2_user] 
	WITH PASSWORD = 0x0200B3358AF015A6D614CA4F1D118B2548840ACAB9EA0B0B408BFD7CB97BE041BE1C67DADAA6EF669A018D881240B928AC423CCD872C8556053B530411AD2DCF6CA97C909399 HASHED
		, SID = 0xD17D14CEA920BE47B65114957A92A0AB
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF;
	RAISERROR('INFO: Login [wi2_user] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [wi2_user] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: SQLLink
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'SQLLink')
BEGIN
	CREATE LOGIN [SQLLink] 
	WITH PASSWORD = 0x0200F6B4337F5D526EE400A760CFF2E70213B6FC93DE3D47C8C83FB0E01426659236409D4DF4BA6C813E94A2537845D39A4638D9B43D9E652445D5B7D5421702EF7F068AD55C HASHED
		, SID = 0x565BECDCE03D5446A77109682B53A7C7
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF;
	RAISERROR('INFO: Login [SQLLink] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [SQLLink] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: MRIFRCInterface_user
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'MRIFRCInterface_user')
BEGIN
	CREATE LOGIN [MRIFRCInterface_user] 
	WITH PASSWORD = 0x010075CD56D0977AAF77BC665492BF6F97D1CC3F97ED710434A7 HASHED
		, SID = 0x8CD0C94306C06E4788766ACF5D0B778B
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [MRIFRCInterface_user] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [MRIFRCInterface_user] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: kfprod_user
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'kfprod_user')
BEGIN
	CREATE LOGIN [kfprod_user] 
	WITH PASSWORD = 0x01005AE9BE1B7E685DE8289BA9E98FD26C6F9FAB533F788B5D48 HASHED
		, SID = 0xF2003DE73C254E4687E7A0C715DB5381
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [kfprod_user] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [kfprod_user] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: KF_ServiceBroker
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'KF_ServiceBroker')
BEGIN
	CREATE LOGIN [KF_ServiceBroker] 
	WITH PASSWORD = 0x01008E3266813F7C09972E26F6FB7031E456C7BB9E144F458ABF HASHED
		, SID = 0xC7F8E1C838A72643921B43AE042EC4F5
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [KF_ServiceBroker] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [KF_ServiceBroker] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: KF_Reports
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'KF_Reports')
BEGIN
	CREATE LOGIN [KF_Reports] 
	WITH PASSWORD = 0x0200FA970511E237B87E0C18B32FFF1BF96B1C060CCDC180C753A9264BA699AB494FA53DACC467B89D9F39EA56BAFA0646111A13B75A40BCCED7639E0767EA0036254B8101AC HASHED
		, SID = 0x1E92B7771BD85A43B3FCC5430A685CA6
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [KF_Reports] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [KF_Reports] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: error_monitor
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'error_monitor')
BEGIN
	CREATE LOGIN [error_monitor] 
	WITH PASSWORD = 0x0100AD85DEC03261983D656871425388C3B80F56BB806B469654 HASHED
		, SID = 0x0318EC7BA47E7846895539D098C11410
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [error_monitor] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [error_monitor] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: connector_user
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'connector_user')
BEGIN
	CREATE LOGIN [connector_user] 
	WITH PASSWORD = 0x010019026B03806E30ED8B5609ADF9467FCCF04CD47A55C22D7F HASHED
		, SID = 0xF08453C2D6C9F64E85E2ADF84651C6BD
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [connector_user] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [connector_user] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: AttachLoad2
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'AttachLoad2')
BEGIN
	CREATE LOGIN [AttachLoad2] 
	WITH PASSWORD = 0x0100DA4A34CDE1455C3CFAD9FBB4FEA54D91588F9A3213D3715E HASHED
		, SID = 0x47861FA46006BD4CBF9481D890ED3946
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [AttachLoad2] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [AttachLoad2] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: AttachLoad
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'AttachLoad')
BEGIN
	CREATE LOGIN [AttachLoad] 
	WITH PASSWORD = 0x01001388B3AE62E11BD15004E5305E1CC5549023146D7C3F5296 HASHED
		, SID = 0xB485FE6D41097644979FBD5F079A9A72
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [AttachLoad] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [AttachLoad] already exists.',10,1) WITH NOWAIT;
END 

-- Login: SSRSDiagnostics
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'SSRSDiagnostics')
BEGIN
	CREATE LOGIN [SSRSDiagnostics] 
	WITH PASSWORD = 0x020060254C58EC6C20DCF4F01AD7FDA893398BEEE1A8510804755CC0AE096A6EA79ADB83641613149A024E18A0506BE016E9574BE11C8C692946345F4C61C2F1CE9C11AC9559 HASHED
		, SID = 0xAD02FCC9E0902E42968B0A572E163CB1
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [SSRSDiagnostics] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [SSRSDiagnostics] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: cdb_user
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'cdb_user')
BEGIN
	CREATE LOGIN [cdb_user] 
	WITH PASSWORD = 0x02008BF712AFCF87978802454580348CBDC95DA9E32E73078A298FA01A43F877FA117D1668D1ADFC4361F8A3357C18824171F02078348D78325BBA13EBE9AB50A66208848D3E HASHED
		, SID = 0x3518337C62A7CE44ADD93E5ED3A4878B
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [cdb_user] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [cdb_user] already exists.',10,1) WITH NOWAIT;
END 
 
-- Login: itportal_user
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'itportal_user')
BEGIN
	CREATE LOGIN [itportal_user] 
	WITH PASSWORD = 0x0200779AB58F808B83E52D69E2029D40346A24A5E92E816573FE45913B90376445AD17578E022046724DDF5825EE8E09A812D6B138927619B8B94D075D681AF5869DCADAC45E HASHED
		, SID = 0x7DB7A06E211B5548809798A89FCEE6FC
		, DEFAULT_DATABASE = [tempdb]
		, DEFAULT_LANGUAGE=[British]
		, CHECK_POLICY = OFF
		, CHECK_EXPIRATION = OFF
	RAISERROR('INFO: Login [itportal_user] created.',10,1) WITH NOWAIT;
END
ELSE
BEGIN
	RAISERROR('INFO: Login [itportal_user] already exists.',10,1) WITH NOWAIT;
END 

-- setup account impersonation
USE [master]
GO
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = N'wi2_user')
	GRANT IMPERSONATE ON LOGIN::[APACKF\SQLService] TO [wi2_user]
GO
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = N'KF_ServiceBroker')
	GRANT IMPERSONATE ON LOGIN::[APACKF\SQLService] TO [KF_ServiceBroker]
GO
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\vreports')
	GRANT IMPERSONATE ON LOGIN::[APACKF\SQLService] TO [APACKF\vreports]
GO
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\visionimageup')
	GRANT IMPERSONATE ON LOGIN::[APACKF\SQLService] TO [APACKF\visionimageup]
GO
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\strestricted')
	GRANT IMPERSONATE ON LOGIN::[APACKF\SQLService] TO [APACKF\strestricted]
GO
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\PAS Development')
	GRANT IMPERSONATE ON LOGIN::[APACKF\SQLService] TO [APACKF\PAS Development]
GO
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\scheduledtasks')
	GRANT IMPERSONATE ON LOGIN::[APACKF\SQLService] TO [APACKF\scheduledtasks]
GO
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = N'APACKF\PAS Development')
	GRANT IMPERSONATE ON LOGIN::[KF_ServiceBroker] TO [APACKF\PAS Development]
GO



